### ISSUE TITLE
OC-1.2 Default address families & PushConfig() method

### ISSUE THREAD

**Issue by LimeHat** [openconfig/featureprofiles#1019]
Current version of the test seems to rely on [PushConfig() method](https://github.com/openconfig/ondatra/blob/3b28896095b89670014dfb197224a83a50a9b5f2/binding/binding.go#L131) for DUT that is not implemented for staticDUT type [in featureprofiles binding.go](https://github.com/openconfig/featureprofiles/blob/edb20b68c532cb40f7e1e545c3f29bbfe2f021ee/topologies/binding/binding.go):
https://github.com/openconfig/featureprofiles/blob/edb20b68c532cb40f7e1e545c3f29bbfe2f021ee/feature/networkinstance/ate_tests/defaults_test/defaults_test.go#L135-L137

Therefore we get an "unimplemented" error message from [embeded PushConfig() method of AbstractDUT type](https://github.com/openconfig/ondatra/blob/8e19d8cde055be8c68f7ff63164df359baf29a1a/binding/abstract.go#L87).
Could you please provide some guidance here, how this should be resolved?

I see two main options:
1) the test could be refactored to remove the call to this method, and instead:
	a) use gNMI replace, and/or
	b) rely on the fact that configs are reset before test exectuion
2) this method should be implemented

What do you think?

cc @Hobbydos @trathod1 @xw-g

**Comment by xw-g** [comment]
@liulk maybe can help comment from the infra side? Thanks.

**Comment by LimeHat** [comment]
I guess #1041 that has just been merged resolves this according to option#1.b. All right then.
