### ISSUE TITLE
Client sees EOF on Sub ONCE as error.

### ISSUE THREAD

**Issue by Hobbydos** [openconfig/featureprofiles#103]
Hi all,
I think I might be seeing one issue when the gNMI server responds with EOF on Sub ONCE, client sees this as failed test.

```
=== RUN   TestInterface/ifname/Get_Interface_Config
    interface_test.go:23: Get(t) at path origin:"openconfig"  elem:{name:"interfaces"}  elem:{name:"interface"  key:{key:"name"  value:"lo0"}}  elem:{name:"config"}  elem:{name:"name"}: error receiving gNMI response: EOF
--- FAIL: TestInterface (0.72s)
    --- FAIL: TestInterface/ifname (0.72s)
        --- FAIL: TestInterface/ifname/Get_Interface_Config (0.72s)
FAIL
*** Releasing the testbed
FAIL	command-line-arguments	1.075s
FAIL
```

**Comment by dplore** [comment]
If the server is only returning EOF, I think that's not compliant with  gNMI subscribe once specification?

https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#35151-once-subscriptions

**Comment by Hobbydos** [comment]
Closing due to bad server implementation of spec. Thanks @dplore
