### ISSUE TITLE
RT 1.3 route_propagation_test.go

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#1078]
Hi,

We are getting below issue while running RT 1.3 route_propagation_test.go. Please could you help to resolve it.
ATE rib verification api calls are failing with render issues.
Do we need to change anything in rib verification API calls ?

Error:
=====
    route_propagation_test.go:417: Await(t) on ate(10.92.196.126) at &{{NetworkInstance_Protocol_Bgp_Rib_AfiSafi_Ipv4Unicast_Neighbor_AdjRibInPre_Route true 0xc0029bfe60 0x5df6480 0x5df6520 0x5df6580 true}}: error receiving gNMI response: failed to render notifications: could not extract set leaves from modified struct: error from ForEachDataField iteration: nil value for key Index
        nil value for key Index
        nil value for key Index
        nil value for key Index
        nil value for key Index
        nil value for key Index
        nil value for key Index
        nil value for key Index

 route_propagation_test.go:429: Await(t) on ate(10.92.196.126) at &{{NetworkInstance_Protocol_Bgp_Rib_AfiSafi_Ipv6Unicast_Neighbor_AdjRibInPre_Route true 0xc005809e00 0x5e75fc0 0x5e76060 0x5e760c0 true}}: error receiving gNMI response: failed to render notifications: could not extract set leaves from modified struct: error from ForEachDataField iteration: nil value for key Index
        nil value for key Index
        nil value for key Index
        nil value for key Index
        nil value for key Index
        nil value for key Index
        nil value for key Index

Thanks,
Prabha

**Comment by greg-dennis** [comment]
@wenovus, can you help us understand the error from ygot.Diff here?

**Comment by wenovus** [comment]
Is it from https://github.com/openconfig/ondatra/blob/main/internal/ixgnmi/ixgnmi.go#L150?
If so, it looks like one of the input `dev` objects has a list element whose key value is missing. So my guess is `fetch` is creating such a list element somehow. This is invalid since all list elements must have its keys populated.

**Comment by cprabha** [comment]
Thanks @greg-dennis , @wenovus .

**Comment by greg-dennis** [comment]
This has been fixed in https://github.com/openconfig/ondatra/releases/tag/v0.1.5

**Comment by cprabha** [comment]
Thanks Greg.  
Is this merged with https://github.com/openconfig/featureprofiles ?

**Comment by greg-dennis** [comment]
@cprabha The featureprofiles go.mod has not been updated to require that latest version of Ondatra, but you can update it independently for your build. I can separately work on updating the featureprofiles go.mod file to require it.

**Comment by greg-dennis** [comment]
@cprabha, featureprofiles has now been updated to require that version of Ondatra as well

**Comment by cprabha** [comment]
Thanks Greg.
Test is working fine now.

-Prabha



Juniper Business Use Only
