### ISSUE TITLE
oc.PacketMatchTypes_IP_PROTOCOL_IP_IN_IP translated as 5 , it should be 4.

### ISSUE THREAD

**Issue by azubaidhar** [openconfig/featureprofiles#1142]
**Describe the bug**

oc.PacketMatchTypes_IP_PROTOCOL_IP_IN_IP ENUM variable takes 5 as value.  It should be 4 (IP-in-IP tunneling).

https://github.com/openconfig/gribigo/blob/c2737bd7779966f45cfb46e910d920b8cf8430a9/aft/oc.go

// PacketMatchTypes_IP_PROTOCOL_IP_IN_IP corresponds to the value IP_IN_IP of PacketMatchTypes_IP_PROTOCOL
	PacketMatchTypes_IP_PROTOCOL_IP_IN_IP E_PacketMatchTypes_IP_PROTOCOL = 5

**To Reproduce**
 --

**Expected behavior**

https://github.com/openconfig/public/blob/master/release/models/acl/openconfig-packet-match-types.yang

  identity IP_IN_IP {
    base IP_PROTOCOL;
    description
      "IP-in-IP tunneling (4)";
    reference
      "RFC2003: IP Encapsulation within IP";
  }

**Comment by liulk** [comment]
I agree that IP-in-IP has the protocol number 4 as the value that appears in the packet IP header, but the enum constant used in the ygot generated code is unrelated to that. The aft/oc.go is ygot generated from the YANG. That particular constant will be represented as the string `"IP_IN_IP"` when serialized to IETF JSON.

In code, if you use oc.UnionInt64(4) that would incorrectly set the enum to `"IP_IGMP"`.

@robshakir @wenovus
