### ISSUE TITLE
Issue with gnmi.WatchAll 

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#1208]
Hi ,

I am getting error while using gnmi.WatchAll() function. Below is the error, please could you check.

Error:
Get(t) on dut at /network-instances/network-instance[name=DEFAULT]/protocols/protocol[identifier=BGP][name=BGP]/bgp/neighbors/neighbor[neighbor-address=192.0.2.10]/afi-safis/afi-safi[afi-safi-name=IPV4_UNICAST]/state/prefixes/sent: failed to receive to data: error receiving gNMI response: rpc error: code = OutOfRange desc = error on request {
        subscribe:  {
          prefix:  {
            target:  "dut:6030"
          }
          subscription:  {
            path:  {
              origin:  "openconfig"
              elem:  {
                name:  "network-instances"
              }
              elem:  {
                name:  "network-instance"
                key:  {
                  key:  "name"
                  value:  "DEFAULT"
                }
              }
              elem:  {
                name:  "protocols"
              }
              elem:  {
                name:  "protocol"
                key:  {
                  key:  "identifier"
                  value:  "BGP"
                }
                key:  {
                  key:  "name"
                  value:  "BGP"
                }
              }
              elem:  {
                name:  "bgp"
              }
              elem:  {
                name:  "neighbors"
              }
              elem:  {
                name:  "neighbor"
                key:  {
                  key:  "neighbor-address"
                  value:  "192.0.2.10"
                }
              }
              elem:  {
                name:  "afi-safis"
              }
              elem:  {
                name:  "afi-safi"
                key:  {
                  key:  "afi-safi-name"
                  value:  "IPV4_UNICAST"
                }
              }
              elem:  {
                name:  "state"
              }
              elem:  {
                name:  "prefixes"
              }
              elem:  {
                name:  "sent"
              }
            }
          }
          mode:  ONCE
          encoding:  PROTO
        }
        }: ID Exhausted

Thanks,
Prabha

**Comment by LimeHat** [comment]
@cprabha as far as I understand, this is an error coming from your DUT
```
rpc error: code = OutOfRange desc = error on request {
...
}: ID Exhausted
```

**Comment by greg-dennis** [comment]
@cprabha, yes, this is the DUT's gnmi response, not related to anything in the WatchAll function itself

**Comment by cprabha** [comment]
Thanks @greg-dennis , @LimeHat .
