### ISSUE TITLE
RT-3.2: Multiple <Protocol, DSCP> Rules for VRF Selection

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#131]

**Comment by cprabha** [comment]
Hi Darren,

This test was assigned to me . I recently started working on RT 3.2 test after I completed automating RT1.1.
Yesterday there is pull requested for this test RT3.2 . please could you let me know if I need to continue automating this test?

https://github.com/openconfig/featureprofiles/pull/214

Thanks,
Prabha

**Comment by cprabha** [comment]
Hi Darren,

RT3.2 test was assigned to me earlier ; I have recently started working on it after completing RT1.1 automation.
Today I could see there is pull request created for RT3.2.

Please could you clarify if the test is still assigned to me ?

Thanks,
Prabha




Juniper Business Use Only

**Comment by cprabha** [comment]
Hi Likai,

Sure, I will provide review for RT 3.2 PR.

Thanks,
Prabha



Juniper Business Use Only
