### ISSUE TITLE
RT-4.1: VRF Fallback

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#132]

**Comment by joannc2022** [comment]
Hi Darren,  

cprabha would like to sign up RT-4.1. Can you assign this test case to her ?  

Thanks,
Joann

**Comment by dplore** [comment]
Hi Joann,  This test is labeled as 'Not Ready' because it has insufficient
description of its requirements and the update of these requirements is
TBD.    Can you choose another test which is labeled 'Ready'?

**Comment by dplore** [comment]
This feature is no longer prioritized for featureprofiles test development.  It may be reopened in the future if there is a use case or sponsor to implement.
