### ISSUE TITLE
TE-4.2: Master Failover

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#144]

**Comment by dplore** [comment]
@sgirishj to be assigned

**Comment by dplore** [comment]
Hi @sgirishj can you let us know how the development is going?

**Comment by sgirishj** [comment]
Hi @dplore, its under internal code review. Planning on pushing it in next week. Thanks!

**Comment by sgirishj** [comment]
Pull request submitted: https://github.com/openconfig/featureprofiles/pull/218

Thanks!
