### ISSUE TITLE
static binding to allow PMD value to be set

### ISSUE THREAD

**Issue by liulk** [openconfig/featureprofiles#1440]
From @ANISH-GOTTAPU:

> We need to add the below check for OTG Hardware, could you please let me know where and how to set the PMD value on the port?
> https://github.com/openconfig/featureprofiles/blob/main/feature/interface/aggregate/ate_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go#L338-L341

We need to make some code changes to the static binding to propagate the information.

In the static binding code [binding.go line 339](https://github.com/openconfig/featureprofiles/blob/087632e6a2036d9a64dcf5e0f5824c94e93e2612/topologies/binding/binding.go#L339), we need to populate the PMD type, either from Ondatra [testbed.proto](https://github.com/openconfig/ondatra/blob/main/proto/testbed.proto) tport.pmd_value.pmd (can't use pmd_regex) or populate it from the [binding.proto](https://github.com/openconfig/featureprofiles/blob/main/topologies/proto/binding.proto) by adding the PMD type there. The former option is probably easier.

If we propagate it from testbed.proto, then specify the pmd in the testbed file like this one: [atedut_4.testbed](https://github.com/openconfig/featureprofiles/blob/main/topologies/atedut_4.testbed). If we propagate it from the binding.proto, then specify the pmd in the binding file [atedut_4.binding](https://github.com/openconfig/featureprofiles/blob/main/topologies/atedut_4.binding).

**Comment by greg-dennis** [comment]
The PMD value in the testbed proto should be used only if the device must have that PMD value as a requirement of the test. If it's not a requirement of the test but the test needs to merely know what the PMD value is then it should be reported back in the binding. It looks to me like the PMD restriction is not a test requirement but the test does need to know what the value is. Is that correct here?

**Comment by ANISH-GOTTAPU** [comment]
@greg-dennis: yes, it is not requirement of the test but the test does need to know what the value is. Based on the PMD value few L1 settings on the port should be changed for the port to come up. (specifically for OTG-HW).

**Comment by ANISH-GOTTAPU** [comment]
Hi @greg-dennis : Do you want any other info, please let me know

**Comment by greg-dennis** [comment]
@ANISH-GOTTAPU, sorry for the delay on this. I'm rereading my answer above, and I'm not quite sure why I went straight to "it should be reported by the binding" as the solution. I first solution should have been: have the test read the PMD value from the binding. Is there a reason that isn't feasible here?

**Comment by ANISH-GOTTAPU** [comment]
@greg-dennis : Anything is fine for me either it is propagated from testbed.proto or binding.proto

My usecase is similar to the below test written for ATE, but for OTG-HW
![image](https://github.com/openconfig/featureprofiles/assets/48308607/2da548da-c1e3-4f85-a755-adbf68736015)
But Likai said the PMD check support is not available yet.

https://github.com/openconfig/featureprofiles/blob/main/feature/interface/aggregate/ate_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go#L338-L341

I want to add the same check for OTG-HW, if we can populate PMD value, I want to read in the test and apply HW settings.
