### ISSUE TITLE
RT-3.1: [Protocol, DSCP]-based VRF Selection

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#149]

**Comment by dplore** [comment]
Hi @smulky can you let us know how the development is going?

**Comment by smulky** [comment]
Hi @dplore https://github.com/openconfig/featureprofiles/pull/228 has been raised for this. Thanks.

**Comment by joannc2022** [comment]
Hi @dplore   

@azubaidhar has raised #712 to merge the script to github.  Please mark this test case Done.  

Thanks,
Joann
