### ISSUE TITLE
gNMI-1.3:  Benchmarking: Drained Configuration Convergence Time

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#171]

**Comment by joannc2022** [comment]
Hi Darren,

cprabha would like to sign up gNMI-1.3. Can you assign this test case to her ?

Thanks,
Joann

**Comment by dplore** [comment]
Assigned, thank you!

**Comment by joannc2022** [comment]
Hi Darren,

cprabha has started #645 for this test case.  Please update status from ready to in-progress.  

Thanks,
joann

**Comment by dplore** [comment]
Thanks.  To link PR to Issue, you can mention the Issue in the PR description.  I updated #645 to do this for us

**Comment by joannc2022** [comment]
As script review is in progress, can someone help this issue status from ready to in-progress ?
