### ISSUE TITLE
gNMI-1.8: annotation_test.go : Configuration Metadata-only Retrieve and Replace

### ISSUE THREAD

**Issue by smulky** [openconfig/featureprofiles#173]
Issue: 
Encoding JSON used instead of JSON_IETF in GetRequest

Question:
Can you please clarify if the script has missed out setting “Encoding” field for GetRequest in this testcase? 
I believe Google would be expecting JSON_IETF to be used as standard.

Testcase:
gNMI-1.8: Configuration Metadata-only Retrieve and Replace

Code reference:
https://github.com/openconfig/featureprofiles/blob/fe7a8c25dcaf8cc3e57e942b153398c34066c595/feature/system/gnmi/metadata/tests/annotation_test/annotation_test.go#L109

Analysis:
It seems that the script is not setting any value(json/json_ietf/proto/…) for ’Encoding’ field of GNMI GetRequest.
		getResponse, err := gnmiClient.Get(context.Background(), &gpb.GetRequest{
			Path: []*gpb.Path{{
				Elem: []*gpb.PathElem{},
			}},
			Type:     gpb.GetRequest_CONFIG,
		})

So  Encoding value is getting set internally  to “0” (Which maps to JSON type) and not JSON_IETF(Encoding:  “4”).

If script is modified to set “Encoding” field to 4 (JSON_IETF)  test passes.
		getResponse, err := gnmiClient.Get(context.Background(), &gpb.GetRequest{
			Path: []*gpb.Path{{
				Elem: []*gpb.PathElem{},
			}},
			Type:     gpb.GetRequest_CONFIG,
			Encoding: 4,   <<<<<
		})

**Comment by dplore** [comment]
The recommendation is that the featureprofiles tests should request JSON IETF encoding instead of leaving it to the default.

**Comment by dplore** [comment]
@liulk any thoughts here?  Seems like we should explicitly use JSON IETF for encoding?

**Comment by sezhang2** [comment]
I added **Encoding: gpb.Encoding_JSON_IETF** under GetRequest for a couple of tests.

We can set the default value to JSON IETF in gnmi proto file to avoid specifying it explicitly for each GetRequest.

**Comment by liulk** [comment]
Yes, it seems that we should specify the JSON_IETF encoding in GetRequest.

**Comment by sezhang2** [comment]
FYI-

I submitted the fix at https://github.com/openconfig/featureprofiles/blob/main/feature/system/gnmi/metadata/tests/annotation_test/annotation_test.go#L114

			   Type:     gpb.GetRequest_CONFIG,
			+ Encoding: gpb.Encoding_JSON_IETF,

Thanks,
Sean

**Comment by sezhang2** [comment]
Close the issue as the fix is committed.
