### ISSUE TITLE
gNOI-5.3 update to fetch artifact

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#1734]
[gNOI-5.3 test](https://github.com/openconfig/featureprofiles/blob/main/feature/gnoi/system/tests/copying_debug_files_test/copying_debug_files_test.go) has a remaining TODO item.  The test must be updated to fetch an artifact indicated by the healthz response.  

That is:

* The test must verify the [healthz get response](ComponentStatus) produces a reresponse for component type CHASSIS
* Invoke the [health check rpc](https://github.com/openconfig/gnoi/blob/6884aef91ca81a8009eb349bcaeb9dbabe80f333/healthz/healthz.proto#L57) for component type CHASSIS to trigger generation of  [Artifact ID(s)](https://github.com/openconfig/gnoi/blob/891b1d10e452f3fc4f4138b5ec80456860b88337/healthz/healthz.proto#LL112C7-L112C7) equivalent to 'show tech support.   
*  Invoke  [ArtifactRequest](https://github.com/openconfig/gnoi/blob/891b1d10e452f3fc4f4138b5ec80456860b88337/healthz/healthz.proto#L150) to transfer the requested artifact ID.  

Pass criteria is 
* getResponse contains valid health data
* Check RPC returns valid CheckResponse
* ArtifactResponse contains data.  Fail is if the ArtifactReponse cannot be successfully retrieved or contains zero data.

**Comment by sgirishj** [comment]
Pull Req https://github.com/openconfig/featureprofiles/pull/1890 opened to resolve this
