### ISSUE TITLE
P4RT-1.1: Base P4RT Functionality

### ISSUE THREAD

**Issue by rsindhujha** [openconfig/featureprofiles#190]
By using the p4runtime-go-client as part of PINS project (https://github.com/pins/p4runtime-go-client), i am able to send "SetForwardingConfigPipeline" with P4Info and "GetForwardingConfigPipeline". Is this is client we can consider to automate this TC P4RT 1.1?

**Comment by dplore** [comment]
This is our leading candidate for p4rt client at the moment.  @hariramnat is in process of reviewing on behalf of the team.

**Comment by rsindhujha** [comment]
Also succesfully tried packetIn scenario just by creating a channel for StreamMessageResponse_Packet and receive traffic from DUT p4 server. Below example is tried from l2_switch example of PINS client

arbitrationCh := make(chan bool)
messageCh := make(chan *p4_v1.StreamMessageResponse, 1000)

I believe Packetout can also be tried similarly.

**Comment by rsindhujha** [comment]
@hariramnat, Is the P4RT client to be used finalized yet?

**Comment by hariramnat** [comment]
Hey @rsindhujha, 
 This particular client does looks promising, I did try out PacketIn and pAcketOut functionality using this in Mininet. However, we are having a syncup next week to finalize which client will we be using for our tests. Will keep you posted with the next steps.

**Comment by dplore** [comment]
p4rt tests are now using the https://github.com/cisco-open/go-p4
