### ISSUE TITLE
route_installation_test.go

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#191]
Hi,

We need to configure network instance type and router-id for BGP in Juniper. Below script needs to be updated with configuration for network instance type and router id.

I have used below configurations to run route_installation_test.go.

set openconfig-network-instance:network-instances network-instance DEFAULT config type DEFAULT_INSTANCE
set openconfig-network-instance:network-instances network-instance DEFAULT config router-id 11.11.11.11

Thanks,
Prabha

**Comment by dplore** [comment]
Hi @cprabha thanks for reporting this issue.  Can you do some investigation and suggest a way to configure this via openconfig?   Then you can submit a PR to update the test to apply this openconfig.   For beginning your investigation, see:

https://github.com/openconfig/public/blob/179880ce3977cb167637ab753598ec9724a8a0a0/release/models/network-instance/openconfig-network-instance.yang#L1149-L1178

**Comment by cprabha** [comment]
Hi Darren,

Thank you.
I have written and validated network instance configuration code.
Please let me know how to open PR.

Thanks,
Prabha

**Comment by cprabha** [comment]
Hi,

I have updated code via https://github.com/openconfig/featureprofiles/pull/226.

Thanks,
Prabha
