### ISSUE TITLE
aggregate_test.go: Changes needed in "setupAggregateAtomically" function

### ISSUE THREAD

**Issue by avaneesh90** [openconfig/featureprofiles#200]
Hi,

We are observing that interface type being a mandatory config for member interface with aggregated ethernet configuration otherwise without type configuration commit will fail.

"config": {
                  "enabled": true,
                  "name": "et-0/0/1",
                  "type": "iana-if-type:ethernetCsmacd".  >>>> Need to enable it
                },

Code changes needed in function "setupAggregateAtomically"  :
After line no 184:

 i.Type = ethernetCsmacd

        if *deviations.InterfaceEnabled {
            i.Enabled = ygot.Bool(true)
        } 

Thanks,
Avaneesh

**Comment by dplore** [comment]
Hi Avaneesh, you may make the changes to the code and submit a pull request which we will review.

**Comment by avaneesh90** [comment]
Fixed in : https://github.com/openconfig/featureprofiles/pull/260
