### ISSUE TITLE
Does binding #ports have to equal testbed #port?

### ISSUE THREAD

**Issue by MarcCharlebois** [openconfig/featureprofiles#2006]
https://github.com/openconfig/featureprofiles/blob/d347cfa32435d4ddfeef3a84e02045138e7d84bf/topologies/binding/binding.go#L380
Is this a hard requirement? It would be nicer if we could use 1 binding file for most (if not all) tests.
Any thoughts on bringing this from an error to a warning?

**Comment by greg-dennis** [comment]
Yes, we are fine with that being a warning ... or better yet, just going away entirely? Want to send us a PR? Separately from that change, @prinikasn will be working on enabling one binding file for all testbeds, using the our open source solver that can solve for a matching testbed.

**Comment by MarcCharlebois** [comment]
Thanks, I'll close this issue and we can continue the discussions on https://github.com/openconfig/featureprofiles/pull/2015
