### ISSUE TITLE
Setting test timeout value from within a test

### ISSUE THREAD

**Issue by sgirishj** [openconfig/featureprofiles#202]
Hi, I am looking to set the RunTime timeout value for a test to something other than the default value of 10 minutes. Is there a way to set it from within the featureprofiles testcase and pass it through fptest.RunTests() to ondatra.RunTests() or set it as a flag inside the test?

Thanks!

**Comment by sgirishj** [comment]
Thanks @greg-dennis! Yes, I have used the option to set the timeout through the command line when invoking the tests. Was wondering if there was a way to set the timeout from within the test code itself, rather than having to pass it through the command line every time when invoking it.

**Comment by liulk** [comment]
I don't think that's currently possible. Consider filing a feature request here: https://github.com/openconfig/ondatra/issues

**Comment by sgirishj** [comment]
Thanks @liulk! Filed https://github.com/openconfig/ondatra/issues/21 for the same.
