### ISSUE TITLE
complete_chassis_reboot.go

### ISSUE THREAD

**Issue by yashikakn** [openconfig/featureprofiles#208]
Hi,
Need help in understanding why the script is reporting FAIL - there are no error messages and the test steps looks like went through just fine. Logs below. 

--- FAIL: TestChassisReboot (614.76s)
    complete_chassis_reboot_test.go:103: DUT software version: [15.01 15.01 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO]
    complete_chassis_reboot_test.go:104:
        *** Fetching gNOI client for 10.92.196.149...
       
        
    --- FAIL: TestChassisReboot/with_delay (611.37s)
        complete_chassis_reboot_test.go:114: DUT boot time before reboot: 1654176977000000000
        complete_chassis_reboot_test.go:121: Send reboot request: method:COLD  delay:120000000000  message:"Reboot chassis with delay"  force:true
        complete_chassis_reboot_test.go:123: Got reboot response: , err: <nil>
        complete_chassis_reboot_test.go:129: Validating DUT remains reachable for at least 120 seconds
        complete_chassis_reboot_test.go:132: Time elapsed 10.25 seconds since reboot was requested.
        complete_chassis_reboot_test.go:142: Get latest system time: got 2022-06-02 07:27:59 -0700 PDT, want newer time than 2022-06-02 07:27:59 -0700 PDT
        complete_chassis_reboot_test.go:132: Time elapsed 25.10 seconds since reboot was requested.
       complete_chassis_reboot_test.go:142: Get latest system time: got 2022-06-02 07:27:59 -0700 PDT, want newer time than 2022-06-02 07:27:59 -0700 PDT
        complete_chassis_reboot_test.go:132: Time elapsed 38.18 seconds since reboot was requested.
        complete_chassis_reboot_test.go:142: Get latest system time: got 2022-06-02 07:27:59 -0700 PDT, want newer time than 2022-06-02 07:27:59 -0700 PDT
        complete_chassis_reboot_test.go:132: Time elapsed 51.26 seconds since reboot was requested.
        complete_chassis_reboot_test.go:142: Get latest system time: got 2022-06-02 07:27:59 -0700 PDT, want newer time than 2022-06-02 07:27:59 -0700 PDT
        complete_chassis_reboot_test.go:132: Time elapsed 64.80 seconds since reboot was requested.
        complete_chassis_reboot_test.go:142: Get latest system time: got 2022-06-02 07:27:59 -0700 PDT, want newer time than 2022-06-02 07:27:59 -0700 PDT
        complete_chassis_reboot_test.go:132: Time elapsed 77.88 seconds since reboot was requested.
        complete_chassis_reboot_test.go:142: Get latest system time: got 2022-06-02 07:27:59 -0700 PDT, want newer time than 2022-06-02 07:27:59 -0700 PDT
        complete_chassis_reboot_test.go:132: Time elapsed 90.95 seconds since reboot was requested.
        complete_chassis_reboot_test.go:132: Time elapsed 104.07 seconds since reboot was requested.
        complete_chassis_reboot_test.go:142: Get latest system time: got 2022-06-02 07:29:59 -0700 PDT, want newer time than 2022-06-02 07:29:59 -0700 PDT
        complete_chassis_reboot_test.go:132: Time elapsed 117.19 seconds since reboot was requested.
        complete_chassis_reboot_test.go:142: Get latest system time: got 2022-06-02 07:29:59 -0700 PDT, want newer time than 2022-06-02 07:29:59 -0700 PDT
        complete_chassis_reboot_test.go:132: Time elapsed 130.27 seconds since reboot was requested.
        complete_chassis_reboot_test.go:134: Time elapsed 130.27 seconds > 120 reboot delay
        complete_chassis_reboot_test.go:149: Wait for DUT to boot up by polling the telemetry output.
        complete_chassis_reboot_test.go:152: Time elapsed 435.48 seconds since reboot started.
        complete_chassis_reboot_test.go:159: Device rebooted successfully with received time: 2022-06-02T07:37:39-07:00
        complete_chassis_reboot_test.go:167: Device boot time: 468.74 seconds
        complete_chassis_reboot_test.go:170: DUT boot time after reboot: 1654180311000000000
        complete_chassis_reboot_test.go:177: DUT software version after reboot: [15.01 15.01 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO 21.2X80-D23.5-EVO]
FAIL

Thanks.

**Comment by bstoll** [comment]
Hi,

It looks like the error is being generated by [this line](https://github.com/openconfig/featureprofiles/blob/c061c57c24bd1b2847522ac9b11c5fef0c8cccf6/feature/gnoi/tests/complete_chassis_reboot/complete_chassis_reboot_test.go#L142).  It seems like the OC path /system/state/current-datetime is returning the same value even though multiple seconds have elapsed between checks.  This test is expecting time to increment regularly.

**Comment by yashikakn** [comment]
@bstoll : Oops. Somehow missed to note that is an error message. Thank you for the quick response.
