### ISSUE TITLE
Add pem file to the allowed file types list

### ISSUE THREAD

**Issue by mojiiba** [openconfig/featureprofiles#2098]
**Describe the bug**
Currently  PEM file is not a allowed file type. However, as we start developing security tests, using PEM file as part of testdata seems necessary. Can you please add PEM file as allowed type. 

**To Reproduce**
Push a code that contains a PEM file such as https://github.com/openconfig/featureprofiles/pull/2092

**Expected behavior**
NA

**Logs**
NA

**Network device platform (please complete the following information):**
 Na

**Additional context**

**Comment by moji1** [comment]
Hi @dplore  thanks for addressing the issue. The check still is failing:
Checking for allowed file types...
```
./internal/security/svid/testdata/ecdsa/ca-ecdsa-key.pem:                                                                                              PEM EC private key
Error: files should be in plain text or non-empty.
./internal/security/svid/testdata/rsa/ca-rsa-key.pem:                                                                                                  PEM RSA private key
Checking for regular files...
Checking for script files...
Please see "Allowed File Types" in CONTRIBUTING.md for detail.
