### ISSUE TITLE
Help needed to resolve errors in pull request https://github.com/openconfig/featureprofiles/pull/201 

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#211]
Hi,

I need help to resolve errors with my pull request  "https://github.com/openconfig/featureprofiles/pull/201 "

1.) go test failed with error code 2 , found below error in logs. 

>>>> Error: Process completed with exit code 2.

Log Path: https://github.com/openconfig/featureprofiles/runs/6732282213?check_suite_focus=true

2.) Static Analysis fails with below error for float64 variable.

Error: vet: feature/experimental/base_bgp_session_parameters/base_bgp_session_parameters_test.go:164:21: cannot use ygot.Float64(holdTime) (value of type *float64) as *uint16 value in assignment
Error: Process completed with exit code 2.

Script code : nv4t.HoldTime = ygot.Float64(holdTime) ( I also tried nv4t.HoldTime = ygot.Float64(float64(holdTime)) )

Path for error: https://github.com/openconfig/featureprofiles/runs/6733110194?check_suite_focus=true

I have defined holdtime as float64 and passing it as float64, still fails with same error.

Thanks,
Prabha

**Comment by LimeHat** [comment]
Hi @cprabha ,
for p.2 you're likely missed the fact that these structures were recently modified in Ondatra, see this commit
https://github.com/openconfig/ondatra/commit/f19ddc0acde622f9aa6a23fec5df53233c898682

So the actual definition of the struct is:
```
// NetworkInstance_Protocol_Bgp_Neighbor_Timers represents the /openconfig-network-instance/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers YANG schema element.
type NetworkInstance_Protocol_Bgp_Neighbor_Timers struct {
	ConnectRetry                 *uint16 `path:"state/connect-retry" module:"openconfig-network-instance/openconfig-network-instance" shadow-path:"config/connect-retry" shadow-module:"openconfig-network-instance/openconfig-network-instance"`
	HoldTime                     *uint16 `path:"state/hold-time" module:"openconfig-network-instance/openconfig-network-instance" shadow-path:"config/hold-time" shadow-module:"openconfig-network-instance/openconfig-network-instance"`
	KeepaliveInterval            *uint16 `path:"state/keepalive-interval" module:"openconfig-network-instance/openconfig-network-instance" shadow-path:"config/keepalive-interval" shadow-module:"openconfig-network-instance/openconfig-network-instance"`
	MinimumAdvertisementInterval *uint16 `path:"state/minimum-advertisement-interval" module:"openconfig-network-instance/openconfig-network-instance" shadow-path:"config/minimum-advertisement-interval" shadow-module:"openconfig-network-instance/openconfig-network-instance"`
	NegotiatedHoldTime           *uint16 `path:"state/negotiated-hold-time" module:"openconfig-network-instance/openconfig-network-instance"`
	RestartTime                  *uint16 `path:"state/restart-time" module:"openconfig-network-instance/openconfig-network-instance" shadow-path:"config/restart-time" shadow-module:"openconfig-network-instance/openconfig-network-instance"`
}

```

**Comment by cprabha** [comment]
Thank you @LimeHat for pointing it out.
 I have updated my repo and fixed this issue now. p2 issue resolved now.

Thanks,
Prabha

**Comment by cprabha** [comment]
Hi,

I have one issue now. test failed with error code 1.

Process completed with exit code 1.

Thanks,
Prabha

**Comment by cprabha** [comment]
It worked fine after moving scripts to ate_tests directory.
