### ISSUE TITLE
ondatra.go:56] PushConfig unimplemented

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#221]
Hi,

I did git pull today morning and unable to run scripts now due to error "ondatra.go:56] PushConfig unimplemented".
It was working before the git pull.

I have debugged the issue further and it shows getting error at below point. It looks like we are trying to execute reset on dut instead of ate.

Is this due to changes pushed in  topologies/binding/binding.go ??? (https://github.com/openconfig/featureprofiles/pull/206)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
func (b *staticBind) reset(ctx context.Context) error {
	for _, bdut := range b.r.GetDuts() {
		if err := applyCli(ctx, bdut, b); err != nil {   ============> gives error here " pushconfig unimplemented"
			return err
		}
		if err := applyGnmi(ctx, bdut, b); err != nil {
			return err
		}
	}
	return nil
}
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Error:
=========
F0607 11:51:04.651470  544968 ondatra.go:56] PushConfig unimplemented

Thanks,
Prabha

**Comment by Ankur19** [comment]
Hi @cprabha Thanks for the heads up! Didn't realize PushConfig() is unimplemented. You can still run the scripts by setting the **pushConfig** variable to _false_ in **staticBind**: https://github.com/openconfig/featureprofiles/blob/main/topologies/binding/binding.go#L44

**Comment by cprabha** [comment]
Hi @Ankur19 
Thank you. I have topology where dut and ate both are present. If I disable pushconfig will it work for ate ?
Please suggest.

**Comment by Ankur19** [comment]
Yes! @cprabha the staticBind.pushConfig variable is only for DUTs and not for ATEs.

**Comment by cprabha** [comment]
Thank you @Ankur19 .
I will try with pushConfig flag set to false.

**Comment by liulk** [comment]
This should be fixed by #225 . Let @Ankur19 know if it's still not fixed.
