### ISSUE TITLE
TE-17.1 VRF selection policy driven TE

### ISSUE THREAD

**Issue by sachendras** [openconfig/featureprofiles#2222]
# Request for New Test Code Implementation Instructions

* The label 'enhancement' is automatically set by this template.
* Add a label for the test priority according to the test requirements. (p0, p1, p2)
* Add a link in this issue description to the README.md for the test requirements.  For example:

Implement code for [TE-17.1 VRF selection policy driven TE](https://github.com/openconfig/featureprofiles/pull/2217) once merged

**Comment by cprabha** [comment]
I have created https://github.com/openconfig/featureprofiles/pull/2519 to address this issue.
