### ISSUE TITLE
RT-7: BGP default policies

### ISSUE THREAD

**Issue by sachendras** [openconfig/featureprofiles#2282]
# Request for New Test Code Implementation Instructions

* The label 'enhancement' is automatically set by this template.
* Add a label for the test priority according to the test requirements. (p0, p1, p2)
* Add a link in this issue description to the README.md for the test requirements.  For example:

Implement code for [RT-7: BGP Default Policies](https://github.com/openconfig/featureprofiles/blob/main/feature/bgp/policybase/otg_tests/default_policies_test/README.md)

**Comment by cprabha** [comment]
I have created pull request to address this issue. https://github.com/openconfig/featureprofiles/pull/2352
