### ISSUE TITLE
PR 218: Google Cloud Build failure

### ISSUE THREAD

**Issue by sgirishj** [openconfig/featureprofiles#229]
Hi, I am unable to access the failure details below for pull request 218.

========
Google Cloud Build / featureprofiles-pr (disco-idea-817)
failed 11 hours ago in 4m 0s

https://github.com/openconfig/featureprofiles/pull/218/checks?check_run_id=6788030851
========

How can I get the above build failure resolved?

Thanks,
Girish

**Comment by Ankur19** [comment]
re-run build succeeded.

**Comment by sgirishj** [comment]
Great, thanks @Ankur19!
