### ISSUE TITLE
/gcbrun in comment doesn't seem to work

### ISSUE THREAD

**Issue by smulky** [openconfig/featureprofiles#237]
Tried commenting PR#228 with /gcbrun multiple times but still the following check is failing. 
featureprofiles-pr (disco-idea-817)

Can you please take a look and let me know?

**Comment by dplore** [comment]
Can you try again?  It seems to be working for me?  Please include a link to a PR where it did not work for you, that may help me debug

**Comment by smulky** [comment]
@dplore here's the PR: https://github.com/openconfig/featureprofiles/pull/228 .

 I commented it again with /gcbrun but featureprofiles-pr fails. Hope i am doing it right.

**Comment by bstoll** [comment]
Hi,

It does work correctly however a project collaborator needed to make the comment for it to execute.  For what it's worth, this test is _extremely_ unlikely to fail for #228.  I started the test for this PR.
