### ISSUE TITLE
potential Bug in policy.json for authz test

### ISSUE THREAD

**Issue by MarcCharlebois** [openconfig/featureprofiles#2454]
https://github.com/openconfig/featureprofiles/blob/65f36d9714ee48d78c19489935ff73d2d9998178/feature/security/gnsi/authz/tests/authz/testdata/policy.json#L70

Should this be: `gnmi.gNMI`? If so I can raise a PR to amend it.

**Comment by ssachinbharadwaj** [comment]
Yes, you are right. It should be "gnmi" instead of "gribi"

**Comment by MarcCharlebois** [comment]
gonna close this tkt and track https://github.com/openconfig/featureprofiles/pull/2540
