### ISSUE TITLE
base_hierarchical_route_installation_test.go : Need to update instance = "default" with instance = "DEFAULT"

### ISSUE THREAD

**Issue by avaneesh90** [openconfig/featureprofiles#248]
Hi ,

As per WBB HLD.

"A default network-instance of type DEFAULT_INSTANCE(reference), named DEFAULT.This network instance is the base network instance that is populated by routing protocols, referred to as the global or default network-instance by various implementations."

Need to update script:
Code changes are below:
const (
ipv4PrefixLen = 30
instance = "DEFAULT"
)

Thanks,
Avaneesh

**Comment by xw-g** [comment]
@dplore for OC community opinion.

**Comment by dplore** [comment]
@avaneesh90 is correct.  In April the naming for the default network instance was clarified to be "DEFAULT" (all caps).

ref:
https://github.com/openconfig/public/blob/e3fa98e0d27cf7fecf75c71d31316f45c83ddfd6/release/models/network-instance/openconfig-network-instance.yang#L1149-L1160

@avaneesh90 , would you like to submit a PR to update this test?

**Comment by bstoll** [comment]
We also need a deviation/vendor bug created for this as some implementations don't work with DEFAULT.

**Comment by dplore** [comment]
@bstoll we can assign to your backlog and address in the future.
