### ISSUE TITLE
OTG BGP sessions won't establish after this commit 5d3701a3f80615fa6e2ba56d814f25365edd4464

### ISSUE THREAD

**Issue by octpetre** [openconfig/featureprofiles#256]
After merging the commit bellow into my OTG branch, the BGP sessions won't establish with the DUT. 
@mojiiba could you please comment?

https://github.com/openconfig/featureprofiles/commit/5d3701a3f80615fa6e2ba56d814f25365edd4464

**Comment by octpetre** [comment]
The w/a is to revert line 26 in internal/deviations/deviations.go to true

_InterfaceEnabled = flag.Bool("deviation_interface_enabled", true,_

**Comment by mojiiba** [comment]
Hi,  there is no need to revert the commit.
you can enable the interface deviation flag explicitly either by passing the flag when you run the tests or by setting it in test code
 
```
deviations.InterfaceEnabled = ygot.Bool(true)
```
