### ISSUE TITLE
RT-1.27: Static route to BGP redistribution

### ISSUE THREAD

**Issue by rohit-rp** [openconfig/featureprofiles#2568]
# Request for New Test Code Implementation Instructions

- Static routes selected for redistribution base on combination of: prefix-set, set-tag
- MED set to value of metric of static route (metric propagation)
- AS-Path set to contain one AS with value provided in configuration
- Local-Preference to a value provided in configuration
- Community list set to defined community set
- BGP protocol next-hop set to value provided in configuration
- Redstribute static-route with "DROP" as the next-hop

Implement code for [RT-1.27](https://github.com/openconfig/featureprofiles/blob/main/feature/bgp/static-route_bgp_redistribution/README.md)

**Comment by dplore** [comment]
implemented at https://github.com/openconfig/featureprofiles/pull/2900
