### ISSUE TITLE
bgp_graceful_restart_test.go

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#274]
Hi,

source/destination address has to be either prefix/32 or  CIDR/mask has to be provided while configuring acl.

1.) a2.SourceAddress = ygot.String(ateDst.IPv4CIDR())  ==> script is sending "192.0.2.6/30" , it does not work. WE need to send either 
                                                                                               192.0.2.4/30   or 192.0.2.6/32 (exact prefix)

2.) We need to update it to configure network instance type.

Thanks,
Prabha

**Comment by dplore** [comment]
Thank you Prabha, this seems reasonable.  Would you like to submit a PR to directly update the test?

**Comment by cprabha** [comment]
Sure Darren. I will submit a PR. 

Thanks,
Prabha
