### ISSUE TITLE
Ixia Issue : Context deadline exceeded error if StartProtcols called immediately after PushConfig.

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#2824]
Hi,

If StartProtocols is called immediately after PushConfig , context deadline exceeded error is found.
Currently we are providing 30 sec sleep after Pushconfig and StartProtocols to avoid this issue. 
We need fix for this issue to avoid sleep time.

   actions_MED_LocPref_prepend_flow_control_test.go:441: 
        *** Pushing config to 127.0.0.1:40051...
    actions_MED_LocPref_prepend_flow_control_test.go:442: 
        *** Starting protocols on 127.0.0.1:40051...
    actions_MED_LocPref_prepend_flow_control_test.go:442: StartProtocols(t) on ATE{Dims:Dims{Name:127.0.0.1:40051 Vendor:VENDOR_UNSPECIFIED HardwareModel: SoftwareVersion: Ports:map[port1:Port{Name:10.92.196.126;1;5 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} port2:Port{Name:10.92.196.126;1;1 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} port3:Port{Name:10.92.196.126;7;7 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} port4:Port{Name:10.92.196.126;7;8 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED}]}}: {
          "code":  4,
          "errors":  [
            "error on request {\ncontrol_state:  {\n  choice:  protocol\n  protocol:  {\n    choice:  all\n    all:  {\n      state:  start\n    }\n  }\n}\n}: context deadline exceeded"
          ]
        }

Thanks,
Prabha

**Comment by hashwini-keysight** [comment]
@cprabha can you help with providing the containers logs for this issue? Please also share the test link.

Instructions on how to collect it is here:
 - https://github.com/open-traffic-generator/otg-examples/tree/main/hw/ixhw-b2b#diagnostics
 
 Also which DUT are you running your test against?

**Comment by octpetre** [comment]
we're not able to reproduce this while trying to run that test (RT-1.32). Our test fails during dut configuration phase

**Comment by cprabha** [comment]
Hi,

Issue is seen even with 30 seconds  delay.
please try running below script.
https://github.com/openconfig/featureprofiles/tree/main/feature/experimental/gribi/otg_tests/vrf_policy_driven_te

Thanks,
Prabha.

**Comment by cprabha** [comment]
Issue is resolved after updating binding file otg timeout value.
