### ISSUE TITLE
rt-5.9 ipv6 ra config

### ISSUE THREAD

**Issue by LimeHat** [openconfig/featureprofiles#2981]
RT-5.9 sets ipv6 RA mode explicitly together with the disabled flag:

https://github.com/openconfig/featureprofiles/blob/c9114a6fde8b77390a1d0de521e2ce777d844d1e/feature/interface/ip/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/disable_ipv6_nd_ra_test.go#L113-L116

It doesn't seem like mode is applicable to this case, since the enum only covers cases where ipv6 RA is enabled ([oc ref](
https://github.com/openconfig/public/blob/4d4aa4b7dd94acfae84e3f567b534116e6bd5ca4/release/models/interfaces/openconfig-if-ip.yang#L1049-L1068)). 

Can the explicit mode config be removed from the test?

cc @MarcCharlebois

**Comment by ampattan** [comment]
@dplore Could you provide an update on the above query?

**Comment by dplore** [comment]
> @dplore Could you provide an update on the above query?

@LimeHat is correct.  Ipv6 ra mode is only valid if enabled=True.

If the goal is to validate unsolicited ra disable, then enable should be set to true
