### ISSUE TITLE
balancing_test.go : Changes needed in "setupAggregateAtomically" function

### ISSUE THREAD

**Issue by avaneesh90** [openconfig/featureprofiles#306]
Hi,

We are observing that interface type being a mandatory config for member interface with aggregated ethernet configuration otherwise without type configuration commit will fail.

"config": {
"enabled": true,
"name": "et-0/0/1",
"type": "iana-if-type:ethernetCsmacd". >>>> Need to enable it
},

Code changes needed in function "setupAggregateAtomically" :
After line no 184:

i.Type = ethernetCsmacd

    if *deviations.InterfaceEnabled {
        i.Enabled = ygot.Bool(true)
    } 
Thanks,
Avaneesh

**Comment by liulk** [comment]
Closing for now. Feel free to reopen if there are additional issues not already addressed.

**Comment by avaneesh90** [comment]
Hi @liulk ,

https://github.com/openconfig/featureprofiles/pull/260 this pull request is having changes for aggregate_test.go
This git issue filed for RT-5.3: Aggregate Balancing (balancing_test.go) testcase

I am going to reopen

**Comment by liulk** [comment]
I see. Are you planning on authoring a PR or would you like us to fix it? The fix should be the same as #260.

**Comment by avaneesh90** [comment]
Yes, it is having same changes , i have done changes , will create pull request soon
