### ISSUE TITLE
gRIBI get RPC issue with Index data type

### ISSUE THREAD

**Issue by Hobbydos** [openconfig/featureprofiles#319]
Passing a string for Next Hop Index in [get_rpc_test_L327](https://github.com/openconfig/featureprofiles/blob/main/feature/gribi/ate_tests/get_rpc_test/get_rpc_test.go#L327), shouldn't it be passing uint64 as per [openconfig-aft-common](https://github.com/openconfig/public/blob/200af096528411e2ba26dc04d2dced4e823c7be9/release/models/aft/openconfig-aft-common.yang#L268)?

**Comment by robshakir** [comment]
This is setting the value of the next-hop within the OpenConfig static routing model, this `NextHop` leaf is specified [here](http://ops.openconfig.net/branches/models/master/docs/openconfig-network-instance.html#network-instances-network-instance-protocols-protocol-static-routes-static-next-hops-next-hop-config-next-hop) as a union of a `string` and `enum` type. The model you referred to here is the AFT model, which is not used for configuration.
