### ISSUE TITLE
route_ack_test missing CIDR 

### ISSUE THREAD

**Issue by Hobbydos** [openconfig/featureprofiles#320]
See the missing CIDR in the following snippet from [L258](https://github.com/openconfig/featureprofiles/blob/main/feature/experimental/gribi/ate_tests/ack_in_presence_other_routes/route_ack_test.go#L258)
```
-       dut.Config().NetworkInstance(instance).Protocol(telemetry.PolicyTypes_INSTALL_PROTOCOL_TYPE_STATIC, "STATIC").Static("203.0.113.0").Replace(t, dutConf)
+       dut.Config().NetworkInstance(instance).Protocol(telemetry.PolicyTypes_INSTALL_PROTOCOL_TYPE_STATIC, "static").Static("203.0.113.0/24").Replace(t, dutConf)
```

**Comment by dplore** [comment]
Feel free to submit this change as a PR and the team will review.  I think you could use the constant `ateDstNetCIDR ` defined for this purpose?

**Comment by Hobbydos** [comment]
created [PR321](https://github.com/openconfig/featureprofiles/pull/321)

**Comment by Hobbydos** [comment]
Closing as PR321 was merged
