### ISSUE TITLE
Default Network-Instance Case

### ISSUE THREAD

**Issue by aredmon8551** [openconfig/featureprofiles#329]
https://github.com/openconfig/featureprofiles/blob/1b105fe0d3bdf7f866dc52aa15e4ea5327be01c1/feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go#L141

Hey @liulk - should this be 'DEFAULT' rather than 'default'?  

https://github.com/openconfig/public/blob/master/release/models/network-instance/openconfig-network-instance.yang#L1184

Concerned that vendors may have diverged in the naming convention used for this - EOS looks to use 'default', Junos uses 'DEFAULT' per the NI model's guidance, not sure about SR-Linux/IOS-XR.

**Comment by aredmon8551** [comment]
Looks like this is under discussion, as well, here:
https://github.com/openconfig/featureprofiles/pull/183

**Comment by earies** [comment]
@dplore for comment here as I believe this was brought up in a few other recent issues/PRs as well

**Comment by dplore** [comment]
`"DEFAULT"` is the correct string.  Requesting @bstoll take this one.

**Comment by dplore** [comment]
Related to #334  #347  #337

**Comment by dplore** [comment]
We will use this issue to track scanning all the tests for references to the default network instance and update strings to use 'DEFAULT'.  @amrindrr will take this up

**Comment by mojiiba** [comment]
Hi @dplore , Can we use deviations.DefaultNetworkInstance rather than the "DEFAULT" for the test cases? Otherwise, we will not be able to use the deviation if is needed.
