### ISSUE TITLE
backup_nhg_test.go : defaultNetworkInstance = "default"

### ISSUE THREAD

**Issue by rsindhujha** [openconfig/featureprofiles#334]
https://github.com/openconfig/featureprofiles/blob/c5eb74180a2d49a30786123b08518b42af4f9415/feature/experimental/backup_nhg/ate_tests/backup_nhg_test/backup_nhg_test.go#L40

Same context as issues #333 and #329 . Shouldn't the NetworkInstance name be "DEFAULT" instead of "default" here?

**Comment by dplore** [comment]
Thanks for reporting this issue, we will address via #329
