### ISSUE TITLE
Aggregate tests question

### ISSUE THREAD

**Issue by Hobbydos** [openconfig/featureprofiles#336]
Are LAGNames limited to ondatra definitions?

```
func LAGName(vendor ondatra.Vendor, i int) (string, error) {
	if i <= 0 {
		return "", fmt.Errorf("LAG index must be >= 1: %d", i)
	}

	switch vendor {
	case ondatra.ARISTA:
		return fmt.Sprintf("Port-Channel%d", i), nil
	case ondatra.CISCO:
		return fmt.Sprintf("Bundle-Ether%d", i), nil
	case ondatra.JUNIPER:
		// Juniper technically allows 0, but the other vendors start with 1.
		return fmt.Sprintf("ae%d", i), nil
	}

	return "", fmt.Errorf("unsupported vendor: %s", vendor)
}
```

```
const (
	// ARISTA vendor.
	ARISTA = Vendor(opb.Device_ARISTA)
	// CISCO vendor.
	CISCO = Vendor(opb.Device_CISCO)
	// DELL vendor.
	DELL = Vendor(opb.Device_DELL)
	// JUNIPER vendor.
	JUNIPER = Vendor(opb.Device_JUNIPER)
	// IXIA vendor.
	IXIA = Vendor(opb.Device_IXIA)
	// CIENA vendor.
	CIENA = Vendor(opb.Device_CIENA)
	// PALOALTO vendor.
	PALOALTO = Vendor(opb.Device_PALOALTO)
	// ZPE vendor.
	ZPE = Vendor(opb.Device_ZPE)
)
```

**Comment by dplore** [comment]
There is a proposal pending on how to consistently implement parsing of vendor interface names.  @bstoll @liulk  for followup.

**Comment by liulk** [comment]
I'm not sure what is the question actually asking, but Ondatra has added a netutil.NextBundleInterface (among others in the netutil package) that abstracts away the vendor differences since some of our code is written. My #356 migrates our code to use their helper. If more vendors need to be supported, feel free to file an issue or PR in Ondatra's repo.

**Comment by Hobbydos** [comment]
@liulk, 
Apologies for the question not being clear, I was a bit rushed when I wrote it down. Allow me to elaborate a bit and provide more context. 

The reason behind asking was when I was testing this against a vendor not listed in per `ondatra.Vendor` resulting in receiving this error: `aggregate_test.go:437: LAGName for vendor VENDOR_UNSPECIFIED: unsupported vendor: VENDOR_UNSPECIFIED`.

I think, as you suggested, I might need to raise an issue in Ondatra's repo.
