### ISSUE TITLE
lsp_updates_test.go

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#337]
Hi ,

Please update Network instance name "default" to "*deviations.DefaultNetworkInstance".
Some providers are supporting "DEFAULT" as network instance name.

ts.DUTConf.GetNetworkInstance(*deviations.DefaultNetworkInstance).GetProtocol(session.PTISIS, session.ISISName).GetIsis().

Thanks,
Prabha

**Comment by dplore** [comment]
This is the same general issue as #329.   A proposal to fix this is at #352
