### ISSUE TITLE
protocl name for static route policy 

### ISSUE THREAD

**Issue by mojiiba** [openconfig/featureprofiles#351]
Hi, a few of the tests (e.g., https://github.com/openconfig/featureprofiles/blob/3da579ef74aa08d90476105630fe213376e67cf1/feature/gribi/tests/gribigo_compliance_test/gribigo_compliance_test.go#L56) configure a static route and use "static" as the protocol name as shown below:

```
/network-instances/network-instance[name=non-default-vrf]
{
  "openconfig-network-instance:config": {
    "name": "non-default-vrf"
  },
  "openconfig-network-instance:name": "non-default-vrf",
  "openconfig-network-instance:protocols": {
    "protocol": [
      {
        "config": {
          "identifier": "openconfig-policy-types:STATIC",
          "name": "static"
        },
        "identifier": "openconfig-policy-types:STATIC",
        "name": "static"
      }
    ]
  }
}
```

This value is vendor specific and we need to have a flag to pass the name. I can have a pull request to add the flag, however I am not sure where do you prefer to add the flag since this will be used by few tests?

**Comment by xw-g** [comment]
@bstoll

**Comment by xw-g** [comment]
I'm ok with starting a flag. @bstoll to comment further.

**Comment by xw-g** [comment]
#600
