### ISSUE TITLE
'Validate paths' fails in validate_paths.go

### ISSUE THREAD

**Issue by smulky** [openconfig/featureprofiles#371]
We are not able to understand where this is coming from since sflow is not used or added in the checkin.

Can you please let us know what I am missing here?

Thanks.

command-line-arguments
Skipping definitions in /home/runner/work/featureprofiles/featureprofiles/openconfig_public/release/models/wifi
E0712 19:02:45.686777    2338 validate_paths.go:345] Feature paths inconsistent with YANG schema:
  file: /home/runner/work/featureprofiles/featureprofiles/feature/sflow/feature.textproto
    line 8: missing from YANG "/sampling/sflow/config/source-address"
    line 17: missing from YANG "/sampling/sflow/state/source-address"
    line 54: missing from YANG "/sampling/sflow/config/sampling-rate"
    line 63: missing from YANG "/sampling/sflow/state/sampling-rate"
exit status 1
make: *** [Makefile:19: validate_paths] Error 1
Error: Process completed with exit code 2.

**Comment by smulky** [comment]
@dplore can someone please help with an update on this? Thanks

**Comment by dplore** [comment]
Can you reference where this is happening?  Is this a CI check that is failing? If yes, please reference the PR.

If it is from a CI check, more than likely you need to rebase / merge with the lastest commit from the main branch.

**Comment by smulky** [comment]
@dplore  its seen during pull request https://github.com/openconfig/featureprofiles/pull/228 while merging code changes with review comments implemented. Please let me know. Thanks

**Comment by bstoll** [comment]
I believe this was resolved with #309.  Let me know if you're still having issues.
