### ISSUE TITLE
Ondatra script "supervisor_switchover_test.go" script using regular expression is hardcoded to check for “Supervisor”

### ISSUE THREAD

**Issue by avaneesh90** [openconfig/featureprofiles#378]
Hi,

Ondatra script "supervisor_switchover_test.go" script using regular expression is hardcoded to check for “Supervisor” that needs to be updated to check based on vendor specific

Code changes needed in below code:

func TestSupervisorSwitchover(t *testing.T) {
	dut := ondatra.DUT(t, "dut")

	r := regexp.MustCompile("^Supervisor[0-9]$")
	supervisors := findMatchedComponents(t, dut, r)

**Comment by dplore** [comment]
@sezhang2 this should use type CONTROLLER_CARD to make it OpenConfig compliant

**Comment by sezhang2** [comment]
> @sezhang2 this should use type CONTROLLER_CARD to make it OpenConfig compliant

Ack, will update the code accordingly.

**Comment by sezhang2** [comment]
Fixed in PR#387
-   https://github.com/openconfig/featureprofiles/pull/387
