### ISSUE TITLE
core_lldp_tlv_population_test.go : panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by yashikakn** [openconfig/featureprofiles#380]
`panic: runtime error: index out of range [0] with length 0
 
goroutine 12 [running]:
testing.tRunner.func1.2({0xba98740, 0xc0015a41c8})
                /usr/local/go/src/testing/testing.go:1209 +0x47e
testing.tRunner.func1()
                /usr/local/go/src/testing/testing.go:1212 +0x350
panic({0xba98740, 0xc0015a41c8})
                /usr/local/go/src/runtime/panic.go:1047 +0x262
github.com/openconfig/featureprofiles/feature/lldp/tests/core_lldp_tlv_population_test_test.verifyNodeTelemetry(0xc001526ea0, 0xc002878c38, 0xc002878c40, 0xc0019d0b00, 0xc0019d0ae0)
                /root/featureprofiles/feature/lldp/tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go:113 +0x5f8
github.com/openconfig/featureprofiles/feature/lldp/tests/core_lldp_tlv_population_test_test.verifyNode(0xc001526ea0, 0xc002878c38, 0xc002878c40, 0xc0019d0b00, 0xc0019d0ae0, 0xc0028dfec0)
                /root/featureprofiles/feature/lldp/tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go:80 +0x65
github.com/openconfig/featureprofiles/feature/lldp/tests/core_lldp_tlv_population_test_test.TestCoreLLDPTLVPopulation(0xc001526ea0)
                /root/featureprofiles/feature/lldp/tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go:58 +0x2fe
testing.tRunner(0xc001526ea0, 0xbfdfa40)
                /usr/local/go/src/testing/testing.go:1259 +0x1db
created by testing.(*T).Run
                /usr/local/go/src/testing/testing.go:1306 +0x673
 `

Getting above runtime error in case where lldp is disabled globally on dut and script is verifying LLDP state of the peer on ate. 
 
Here, since LLDP is still enabled on ate, the interfaces will still be listed but there won’t be any neighbors on that interface though. 
The check in the script to make sure there are no neighbors is based on the interfaces presence: 
https://github.com/openconfig/featureprofiles/blob/main/feature/lldp/tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go#L102 
 
In the discussed case, this code check fails as LLDP is enabled on ate(hence interface is present) and the code go ahead and try to fetch the LLDP port neighbor ID on peer and panic @ 
https://github.com/openconfig/featureprofiles/blob/main/feature/lldp/tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go#L113 
 
Could you please investigate?
 
Thanks.

**Comment by Ankur19** [comment]
This should be fixed with #415
