### ISSUE TITLE
Replace being used to delete config in RT1.4

### ISSUE THREAD

**Issue by singh-prem** [openconfig/featureprofiles#388]
Testcase RT1.4 is currently using replace for deleting configuration which is against gnmi spec.
		dutConfPath.Replace(t, nil)
https://github.com/openconfig/featureprofiles/blob/f4f5615e33871f5d0de67ff5a53e342c01937b8e/feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go#L395

GNMI spec says:
replace MUST not be used as a way to delete configuration at the path specified by being supplied with a null or invalid value. 
For example, if the boolean b is provided a nil value instead of a boolean value, the target MUST reject this operation by returning 
INVALID_ARGUMENT.

https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#344-modes-of-update-replace-versus-update

**Comment by dplore** [comment]
Thanks @singh-prem ,  like #389 , would you like to submit a PR to fix this issue?  It would be greatly appreciated.  The solution is to change from replace to delete

ref: https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#346-deleting-configuration

Example from another test: https://github.com/openconfig/featureprofiles/blob/b8054dcbfa3c998035fd2dc8940991dd314553fc/feature/interface/aggregate/ate_tests/aggregate_test/aggregate_test.go#L200

**Comment by singh-prem** [comment]
sure @dplore , you could assign this to me

**Comment by singh-prem** [comment]
Raised https://github.com/openconfig/featureprofiles/pull/406 to fix this
