### ISSUE TITLE
RT-1.3: BGP Route Propagation needs uplifting for router-id, global address family, route-policy for ebgp

### ISSUE THREAD

**Issue by singh-prem** [openconfig/featureprofiles#391]
RT-1.3: BGP Route Propagation currently does not have 
1. router-id
2. global address family initialization such that initialized address family can be used under neighbors
3. route-policy used for filtering for an ebgp session

I can take up uplifting this test if no-one has any issues

**Comment by trathod1** [comment]
Observing same issue. Script failing due to - 
       1. Missing PeerGroup configuration with route-policy (required for ebgp) and address-family enabling.
       2. Missing Address-family configuration at global and neighbor (ipv4)

**Comment by xw-g** [comment]
is this related to this PR? https://github.com/openconfig/featureprofiles/pull/513

**Comment by bstoll** [comment]
Closing as this does appear to be resolved by that PR.
