### ISSUE TITLE
gNOI-5.2: traceroute test : Remove hardcoded loopback0 interface

### ISSUE THREAD

**Issue by avaneesh90** [openconfig/featureprofiles#394]
Hi,

https://github.com/openconfig/featureprofiles/blob/main/feature/gnoi/system/tests/traceroute_test/traceroute_test.go#L85

lo0 := dut.Telemetry().Interface("Loopback0").Subinterface(0)

Similar issue was fixed in https://github.com/openconfig/featureprofiles/issues/148 

Same fix is needed in gNOI-5.2: traceroute test.

Thanks

**Comment by sezhang2** [comment]
Created a similar PR for traceroute test at https://github.com/openconfig/featureprofiles/pull/401

**Comment by sezhang2** [comment]
The issue has been fixed 
  - https://github.com/openconfig/featureprofiles/pull/401
