### ISSUE TITLE
MTU changes done in pull #431 seems to cause breakage in other scripts(bgp_prefix_limit, route_installation)

### ISSUE THREAD

**Issue by adityayennam** [openconfig/featureprofiles#445]
Hi ,

The changes related to the MTU calculation that was done as part of the https://github.com/openconfig/featureprofiles/pull/431/files   seems to be causing other scripts (like bgp_prefix_limit, RT-1.2_route_installation) to fail at the mtu configuration .

Error log  from script :
========
nil> <nil> <nil> 0xc00142d5c0 <nil> 0xc0001c8f50 <nil> <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> 0xc0013edbb0 0xc00142d5b0 out-of-range E_Interface_OperStatus enum value: 0 [] [] <nil> map[0:0xc001430a00] out-of-range E_VlanTypes_TPID_TYPES enum value: 0 <nil> ethernetCsmacd}) at path origin:"openconfig"  elem:{name:"interfaces"}  elem:{name:"interface"  key:{key:"name"  value:"et-0/0/5"}}  target:"dut": SetRequest unsuccessful: rpc error: code = Unknown desc = Value 14 is not within range (288..16000);
 

==================
#431 
Diff that’s causing the breakage. MTU if not explicitly set in the caller, gets initialized to 0 and then the diff below causes it to be set to 14.

internal/attrs/attrs.go
                if !*deviations.OmitL2MTU {
                                intf.Mtu = ygot.Uint16(a.MTU + 14)
                }

**Comment by liulk** [comment]
#451 should fix this. Apologies for the bad change.
