### ISSUE TITLE
RT-6.1: During verifyNodeConfig conf.GetChassisId is empty

### ISSUE THREAD

**Issue by trathod1** [openconfig/featureprofiles#460]
In "core_lldp_tlv_population_test.go" script, when configureNode() is called, it configures only lldp.Enabled()  and lldp.Interface(). However, after that when verifyNodeConfig() is called, script try to fetch conf.GetChassisId() which was not configured.

In script logs I see following error -
   core_lldp_tlv_population_test.go:103: LLDP ChassisId got: C0:14:B8:2B:E1:29, want: .
   core_lldp_tlv_population_test.go:109: LLDP SystemName got: MVSRLHW15-DUT2, want: .

Here, conf.GetChassisId() and conf.GetSystemName() is not returning any values, I understand, as we are not configuring it.
In the same function, state.GetChassisId() and state.GetSystemName() is returning proper state values as expected.

Is it expected to fetch conf.GetChassisId() to get value which is not configured by the script ?

Please help investigate, I am not sure, if I am missing something here.

**Comment by yashikakn** [comment]
Facing same issue.

core_lldp_tlv_population_test.go:103: LLDP ChassisId got: 11:33:98:4a:03:10, want: .
core_lldp_tlv_population_test.go:106: LLDP ChassisIdType got: MAC_ADDRESS, want: out-of-range E_LldpTypes_ChassisIdType enum value: 0.
core_lldp_tlv_population_test.go:109: LLDP SystemName got: r1-dut1, want: .

Thanks.

**Comment by dplore** [comment]
I think the expectation is that chassis-id would also be used in LLDP updates.    The test should allow any string to be returned in the chassisid.  Would you like to submit a PR to fix it?

**Comment by azubaidhar** [comment]
Have done the changes and raised a PR https://github.com/openconfig/featureprofiles/pull/599, Please review.

Thanks,
Abdul Zubaidhar .A
