### ISSUE TITLE
TE-5.1: NextHop Index for Static Protocol is used as alphanumeric string instead of integer string

### ISSUE THREAD

**Issue by trathod1** [openconfig/featureprofiles#466]
While executing get_rpc_test.go script, it is observed that during the below call of GetOrCreateNextHop, the index is passed as alphanumeric string - 
       static.GetOrCreateNextHop("AUTO_0").NextHop = telemetry.UnionString(atePort2.IPv4)

Considering it is an index, should it be a numeric (as a string like "0") ?

During execution script is hitting below error - 
       [InvalidArgument] failed to set .network-instance{.name=="DEFAULT"}.next-hop-groups.group{.name=="oc-static-198.51.100.192/26"}.nexthop{.index==0}.index - Invalid value "AUTO_0": Must be an integer in range 0..65535

**Comment by xw-g** [comment]
Can you help translate your thought/suggestions to a PR and link here? Thanks. I'll help review or triage the review. Thanks!

**Comment by trathod1** [comment]
Sure. Let me llink a PR for your review here. Thanks!

**Comment by trathod1** [comment]
PR raised for this - https://github.com/openconfig/featureprofiles/pull/692

**Comment by trathod1** [comment]
PR Merged.
