### ISSUE TITLE
RT-1.2: BGP Policy & Route Installation

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#478]
Hi,

In RT1.2 route_installation_test.go script, We need to add default instance type at line number 467 and 524 before configuring router id. like below,

	dutConfNIPath.Type().Replace(t, telemetry.NetworkInstanceTypes_NETWORK_INSTANCE_TYPE_DEFAULT_INSTANCE)  

Please could you update it.

Thanks,
Prabha

**Comment by singh-prem** [comment]
@cprabha, @dplore  above xpaths are not part of any of the published HLD. 
Ref - https://github.com/openconfig/featureprofiles/issues/392
Implementing above may break this test for other vendors. 
My suggestion get it fixed in the router sw.

**Comment by singh-prem** [comment]
Please note: https://github.com/openconfig/featureprofiles/issues/393 is raised to address the issue of use of router-id outside HLD required xpath for RT1.2.

**Comment by cprabha** [comment]
@singh-prem , this isue is created to add instance type for network instance.
