### ISSUE TITLE
OTG: RT-5.2: Aggregate Interfaces

### ISSUE THREAD

**Issue by octpetre** [openconfig/featureprofiles#558]
- [README](https://github.com/openconfig/featureprofiles/blob/main/feature/interface/aggregate/otg_tests/aggregate_test/README.md)

**Comment by octpetre** [comment]
#556

**Comment by dplore** [comment]
resolved by #556

**Comment by octpetre** [comment]
Fixes #556

**Comment by octpetre** [comment]
Fixes #556
