### ISSUE TITLE
On ATE ttl/HopLimit can not be configured value 0

### ISSUE THREAD

**Issue by ArpitJoshi18** [openconfig/featureprofiles#579]
Below file configures IPv4 traffic fields, it has explicit check for 'ttl > 0'. 
Can we modify this to "ttl >= 0', which helps to create traffic with ttl=0?
https://github.com/openconfig/ondatra/blob/cf83474b5941d335610f7b61cdafeaf6f8a52763/internal/ate/stacks.go#L185

Similarly changes are requires in IPv6 also for HopLimit >=0, below is the file for IPv6.
https://github.com/openconfig/ondatra/blob/cf83474b5941d335610f7b61cdafeaf6f8a52763/internal/ate/stacks.go#L217

**Comment by greg-dennis** [comment]
I fixed this issue in the latest Ondatra commit. The suggested fix (checking ttl >= 0) was not the right fix, since 0 was used to mean "unspecified"; also the value has a uint, so that condition would have been trivially true. I instead made the field optional.
