### ISSUE TITLE
Is Pre-Config required for script execution ?

### ISSUE THREAD

**Issue by trathod1** [openconfig/featureprofiles#607]
While running featureprofiles scripts, it is observed that scripts configures the subinterfaces but does not add those subinterfaces to the required `Network-Instance` like `DEFAULT`. 

Due to this, interface connectivity between DUT and ATE does not come up. 

It is observed on multiple scripts like - 

>      TE-1.1: feature/interface/staticarp/ate_tests/static_arp_test/static_arp_test.go
>      TE-5.1: feature/gribi/ate_tests/get_rpc_test/get_rpc_test.go
>      TE-2.1: feature/gribi/ate_tests/ipv4_entry_test/ipv4_entry_test.go
>      TE-3.1: feature/bgp/policybase/ate_tests/route_installation_test  

Is it required to add subinterfaces as pre-config to the networkinstance?  However, this does not seem scalable.
Is there any common flag/setting to enable this config ? Or script needs to be updated to configure subinterface in network-instance ?

**Comment by dplore** [comment]
This may be related to #624

**Comment by xw-g** [comment]
@xw-g

**Comment by bstoll** [comment]
The current short answer is there is an assumption that interfaces must belong to some network-instance, and the absence of an assignment means the interface is assigned to the default network instance.

**Comment by xw-g** [comment]
+1 to @bstoll 's comment that, by default the interface should be assigned to the default NI, unless it's specifically mentioned by the test case that an interface should be assigned to a NI. 

@trathod1 does this answer your question?

**Comment by trathod1** [comment]
Thanks @bstoll and @xw-g. This answers my query.
