### ISSUE TITLE
TE-13.2: gRIBI route DELETE during failover

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#608]

**Comment by joannc2022** [comment]
Hi Darren,

cprabha would like to sign up TE-13.2. Can you assign this test case to her ?

Thanks,
Joann

**Comment by dplore** [comment]
Assigned, thank you.  @sachendras @r1chance  FYI

**Comment by joannc2022** [comment]
TE-13.2 completed https://github.com/openconfig/featureprofiles/pull/1027 merged.  
Please update Status to Done.  Thanks

**Comment by sachendras** [comment]
Done

**Comment by cprabha** [comment]
completed : https://github.com/openconfig/featureprofiles/pull/1027
