### ISSUE TITLE
Configuration cleanup/teardown after script execution 

### ISSUE THREAD

**Issue by trathod1** [openconfig/featureprofiles#611]
Is there a way to have configuration clean-up/teardown done after the test execution in the script ?

After execution of script `feature/gribi/ate_tests/get_rpc_test/get_rpc_test.go`, it is observed that static-route configurations are left on the DUT for route `198.51.100.192/26`. 

Due to this old static-route, test is failing in `feature/gribi/ate_tests/ipv4_entry_test/ipv4_entry_test.go`.

**Comment by dplore** [comment]
We expect that the device configuration is cleaned up / reset to a default state inbetween each test.  Our expectation is your binding or CI system would perform the configuration reset after completion of a test.

**Comment by trathod1** [comment]
Thanks. Able to use `config` option in binding file to reset config.
