### ISSUE TITLE
Ixia API call support

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#627]
Hi,

We need ixia ondatra API call support to verify below on ATE.

ISIS :
===
i.)	Verifying overload bit on ISIS session
ii.)	Verifying metric on ISIS session.

BGP:
========
i.)	Verifying AS PATH in BGP rib route information

Thanks,
Prabha

**Comment by bstoll** [comment]
This is probably a better question for the [openconfig/ondatra](https://github.com/openconfig/ondatra) team.  If these end up being big asks, it might be that we want to invest time an OTG-only version of these features.

**Comment by cprabha** [comment]
Thanks @bstoll .
Ixia support has opened ticket with openconfig/Ondatra, I will close this ticket.
