### ISSUE TITLE
P4RT-1.1: Base P4RT Functionality

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#64]

**Comment by joannc2022** [comment]
Hi Darren, 

Have P4RT Client decision made yet ?  Can you consider assign this one for Sindhujha [rsindhujha](https://github.com/rsindhujha) ?

**Comment by dplore** [comment]
We are narrowing down to a single option at this time.  I expect to have a decision on the first client to try on Aug 10th.  

We have narrowed the list of candidate P4RT clients to the following:
https://github.com/antoninbas/p4runtime-go-client
https://github.com/cisco-open/go-p4

**Comment by joannc2022** [comment]
Hi Darren, 

rsindhujha have go script ready on this one using p4runtime-go-client. Can you assign it to her? Thanks!
