### ISSUE TITLE
TE-1.2: My Station MAC

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#669]

**Comment by joannc2022** [comment]
@dplore ,      

@yashikakn would like to sign up TE-1.2. Can you assign this test case to her ?

Thanks,
Joann

**Comment by dplore** [comment]
@xw-g can you confirm if this test is ready for implementation?

**Comment by xw-g** [comment]
Yes, the test case is ready.

**Comment by dplore** [comment]
@yashikakn can you give us an estimated date for completion of the implementation for this test case?

**Comment by yashikakn** [comment]
Hi Darren, 
I shall target for 1/17. 
Thanks
