### ISSUE TITLE
P4RT-2.1: P4RT Election

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#72]

**Comment by Hobbydos** [comment]
Hi @dplore, would you consider assigning this case to me?

**Comment by dplore** [comment]
Thanks @Hobbydos , I have assigned to you.  Please let us know when you expect to send a PR for this test. Thanks!

**Comment by Hobbydos** [comment]
No Problem, just assessing the timeline and will comment with an estimated time.
As for now, it seems like [This comment on Issue 64](https://github.com/openconfig/featureprofiles/issues/64#issuecomment-1227718578) seems to hint that `p4runtime-go-client` is the preferred client. One clarification I would like is if there's a preference for featureprofiles to use either `p4runtime-go-client` or `go-p4`.

**Comment by dplore** [comment]
Hi, the preferred client is now https://github.com/cisco-open/go-p4.   Please use the client for your test implementation.  Note, we acknowledge this is a new work and the p4rt tests here are also without much precedent.  We welcome feedback on your findings using this client.

**Comment by Hobbydos** [comment]
@dplore

I have a quick question regarding the handling of multiple P4RT tests. P4RT-3.1 and P4RT-3.2, election IDs are being used `(0,100=primary)`, `(0,99=secondary)` and I've observed that in two different vendor implementations of P4RT, the highest election ID is kept track. When featureprofile tests are ran sequentially, the P4RT server might remember the highest election ID until the P4RT server is restarted. Any following script using lower election ID for its clients will cause the client to fail to be elected as primary. Are there any expectations that users are to handle restarting the P4RT server via bindings file/CI process? If not, is there a proposed alternative?

**Comment by dplore** [comment]
@robshakir @Ankur19 this is a common issue with gRIBI as well.  Should we update our tests to have the client assume primary using a methodology like described in the[ gRIBI spec](https://github.com/openconfig/gribi/blob/595c2f2e3c1635f75dc79cc97eddf62720990f1d/doc/specification.md#4121-election-id-reset).   Are p4rt and gRIBI elections using the same algorithm?

**Comment by Hobbydos** [comment]
PR https://github.com/openconfig/featureprofiles/pull/849

**Comment by Hobbydos** [comment]
Renamed the test to "P4RT Election" to be more inclusive.

**Comment by Hobbydos** [comment]
PR849 was merged
