### ISSUE TITLE
Support needed to configure Set MED routing policy : "GetOrCreateSetMed"

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#759]
Hi,

We need support for the API "GetOrCreateSetMed" to configure routing policy to enable Set MED .

Thanks,
Prabha

**Comment by wenovus** [comment]
Hi Prabha, I believe you're referring to ygot-generated API. I believe `SetMed` is a [leaf](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-routing-policy.html#routing-policy-policy-definitions-policy-definition-statements-statement-actions-bgp-actions-config-set-med) and so you should have a `SetSetMed` setter API available. `GetOrCreatexxx` is for YANG container/lists

**Comment by cprabha** [comment]
@wenovus bgpactions struct points to below . SetMed is "RoutingPolicy_PolicyDefinition_Statement_Actions_BgpActions_SetMed_Union " .  

Where as setLocalPref is uint32 , it works. Please could you check ?


Code which I have tried:
=================
actions5.GetOrCreateBgpActions().SetMed = UnionUint32(bgpMED)  -> did not work 
	actions5.GetOrCreateBgpActions().SetMed = ygot.Uint32(bgpMED) -> did not work
	actions5.GetOrCreateBgpActions().SetLocalPref = ygot.Uint32(100) - works fine.

bgpactions struct:
===============

// RoutingPolicy_PolicyDefinition_Statement_Actions_BgpActions represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions YANG schema element.
type RoutingPolicy_PolicyDefinition_Statement_Actions_BgpActions struct {
	SetAsPathPrepend *RoutingPolicy_PolicyDefinition_Statement_Actions_BgpActions_SetAsPathPrepend `path:"set-as-path-prepend" module:"openconfig-bgp-policy"`
	SetCommunity     *RoutingPolicy_PolicyDefinition_Statement_Actions_BgpActions_SetCommunity     `path:"set-community" module:"openconfig-bgp-policy"`
	SetExtCommunity  *RoutingPolicy_PolicyDefinition_Statement_Actions_BgpActions_SetExtCommunity  `path:"set-ext-community" module:"openconfig-bgp-policy"`
	SetLocalPref     *uint32                                                                       `path:"state/set-local-pref" module:"openconfig-bgp-policy/openconfig-bgp-policy" shadow-path:"config/set-local-pref" shadow-module:"openconfig-bgp-policy/openconfig-bgp-policy"`
	SetMed           RoutingPolicy_PolicyDefinition_Statement_Actions_BgpActions_SetMed_Union      `path:"state/set-med" module:"openconfig-bgp-policy/openconfig-bgp-policy" shadow-path:"config/set-med" shadow-module:"openconfig-bgp-policy/openconfig-bgp-policy"`
	SetNextHop       RoutingPolicy_PolicyDefinition_Statement_Actions_BgpActions_SetNextHop_Union  `path:"state/set-next-hop" module:"openconfig-bgp-policy/openconfig-bgp-policy" shadow-path:"config/set-next-hop" shadow-module:"openconfig-bgp-policy/openconfig-bgp-policy"`
	SetRouteOrigin   E_BgpPolicy_BgpOriginAttrType                                                 `path:"state/set-route-origin" module:"openconfig-bgp-policy/openconfig-bgp-policy" shadow-path:"config/set-route-origin" shadow-module:"openconfig-bgp-policy/openconfig-bgp-policy"`
}

Thanks,
Prabha
