### ISSUE TITLE
RT2.1 base_adjacencies_test.go

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#808]
**Describe the bug**
RT2.1 base_adjacencies_test.go, has checks to verify CSN/LSP packet counters . Test runs on DUT-ATE topology.
ATE is sending CSN/LSP packets before the adjacency is fully up. Hence DUT discards packets and updates counters with
dropped packet count.

Test is checking for zero value for dropped CSN/LSP packets and fails.

It is Ixia issue and ixia support team has fixed the issue. WE need to apply this patch on appserver when we run test.

**To Reproduce**
Run the test with ixia will reproduce this issue.

**Expected behavior**
Ixia should not send CSN/LSP before adjacency is fully up.

**Logs**
--- FAIL: TestBasic/counters_after_adjacency (149.05s)
        --- FAIL: TestBasic/counters_after_adjacency/csnp/state/processed (60.01s)
        --- PASS: TestBasic/counters_after_adjacency/lsp/state/processed (2.28s)
        --- PASS: TestBasic/counters_after_adjacency/psnp/state/processed (2.19s)
        --- FAIL: TestBasic/counters_after_adjacency/packet_counters (37.24s)
            --- FAIL: TestBasic/counters_after_adjacency/packet_counters/csnp/state/processed (3.39s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/csnp/state/received (2.11s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/csnp/state/sent (2.31s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/psnp/state/processed (2.13s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/psnp/state/received (2.53s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/psnp/state/sent (2.09s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/lsp/state/processed (2.14s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/lsp/state/received (2.10s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/lsp/state/sent (2.11s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/iih/state/processed (2.31s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/iih/state/received (2.09s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/iih/state/sent (2.10s)
            --- FAIL: TestBasic/counters_after_adjacency/packet_counters/csnp/state/dropped (2.11s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/psnp/state/dropped (3.50s)
            --- FAIL: TestBasic/counters_after_adjacency/packet_counters/lsp/state/dropped (2.11s)
            --- PASS: TestBasic/counters_after_adjacency/packet_counters/iih/state/dropped (2.10s)

**Comment by cprabha** [comment]
Hi,

CSN/LSP packets counters update depends on Peer and not DUT. If DUT receives them it will update counters accordingly.
So we need to modify the verification depending on packets received/processed/dropped. 
If received is non zero, then processed/dropped either of the counter will be non zero depending adjacency status.
Can we update test based on this ?

Thanks,
Prabha

**Comment by dan-lepage** [comment]
Thanks, Prabha. I think this is the right solution - all our tests necessarily assume that the ATE is behaving properly.

**Comment by joannc2022** [comment]
@sachendras  Ixia has provided patch to Prabha to confirm the fix for CSN/LSP packets counters issues.  The fix is present in  recent release 9.30 OS @ https://support.ixiacom.com/version/ixnetwork-930
