### ISSUE TITLE
bgp password should not be compared

### ISSUE THREAD

**Issue by dplore** [openconfig/featureprofiles#823]
https://github.com/openconfig/featureprofiles/blob/9cb1fb01678a7d96a56ee4871556e77b0b5dbef3/feature/bgp/tests/local_bgp_test/local_bgp_test.go#L224-L236

Setting the password is ok, but the comparison logic in https://github.com/openconfig/featureprofiles/blob/9cb1fb01678a7d96a56ee4871556e77b0b5dbef3/feature/bgp/tests/local_bgp_test/local_bgp_test.go#L314 will fail as it expects an exact match.   Instead, the password should not be compared to the configuration as we expect a DUT to obfuscate the password.

**Comment by cprabha** [comment]
@dplore ,  I have updated RT1.7 Local bgp test with separate verification for password telemetry as in pull request #730  , Please check.  
https://github.com/openconfig/featureprofiles/pull/730/files#diff-b568d01d4e3f86cd28589f4cd53cf2beac8a936b837a504b217969ed9016499d

**Comment by dplore** [comment]
Resolved by #730
