### ISSUE TITLE
gNMI-1.10_Telemetry_Basic_Check : Supervisor is hardcoded in script

### ISSUE THREAD

**Issue by avaneesh90** [openconfig/featureprofiles#829]
Hi ,

Supervisor is hardcoded in script Supervisor[0-9]
regexpPattern := "^Supervisor[0-9]"

Need to change .

Thanks,
Avaneesh

**Comment by sachendras** [comment]
Can we rather update the test to dynamically derive the name from "/components/component[name=" and use that in the test instead? Controller_Card can be referenced differently by different implementations.

**Comment by sachendras** [comment]
@dplore @robshakir @vcheny @xw-g @vosipchu for visibility and suggestions

**Comment by sachendras** [comment]
@avaneesh90 .. will you please send a PR to express the changes in my first comment?

**Comment by dplore** [comment]
Agreed, the test should be refactored to validate identity (type) controller_card and parent of that should be identity (type) chassis.  Same goes for other paths which contain regex matches.  The test should match on the identities defined in openconfig and not the component name strings which are vendor specific .  

I do think it is good that the test validates the parent of a controller_card is chassis as this is expected for operational use cases.  The readme could be updated to reflect this.

**Comment by sachendras** [comment]
Thanks Darren

The later part though in your comment "I do think it is good that the test validates the parent of a controller_card is chassis"

In this particular example may be all implementations today are in sync. But if there is a new implementation in future that probably is not in sync on the exact mapping between a card and the parent (not necessarily just control_card and chassis mapping), the test will fail. As this test mandates that the vendors follow the child parent relationship, doesn't that make the test brittle?

**Comment by sgirishj** [comment]
@sachendras, closing this issue. Will raise a pull request once we are ready with the suggested code changes. Thanks!
