### ISSUE TITLE
gNMI-1.5: Telemetry: Port Speed Test if-ethernet port speed

### ISSUE THREAD

**Issue by avaneesh90** [openconfig/featureprofiles#903]
Hi ,

Port speed does not match the openconfig script expected value for 400G port interface.
Script expect  out-of-range E_IfEthernet_ETHERNET_SPEED enum value: 0
where as the device responds with SPEED_400GB

Yang file using
https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-if-ethernet.yang

identity SPEED_400GB {
    base ETHERNET_SPEED;
    description "400 Gbps Ethernet";
  }

fpoc/enum.go is using https://github.com/openconfig/featureprofiles/blob/main/yang/fpoc/enum.go#L2250
Please suggest us what enum should use .

Thanks,
Avaneesh

**Comment by dplore** [comment]
@wenovus sounds like we need to update to a more recent openconfig release

**Comment by wenovus** [comment]
@avaneesh90 could you provide more details? What is the ondatra version in your go.mod? "SPEED_400GB" seems to be a valid enum in the generated code: https://github.com/openconfig/ondatra/blob/main/gnmi/oc/enum_map.go#L799

**Comment by avaneesh90** [comment]
@wenovus ondatra version using in go.mod is : github.com/openconfig/ondatra v0.0.0-20221212200636-7d597f5e3308

**Comment by wenovus** [comment]
Are you sure a value was received? If the enum was unrecognized, then you should rather get this error:
https://github.com/openconfig/ygot/blob/7baa5b4b783a0274077b66a3852751c114ff2415/ytypes/util_types.go#L143-L146

I can see `SPEED_400GB` in the enum map at this Ondatra version. Indeed I'm not sure if this enum had been changed for a long time: https://github.com/openconfig/ondatra/blob/7d597f5e3308250778e90ff06cc866245e277f6b/gnmi/oc/enum_map.go#L799

**Comment by avaneesh90** [comment]
Hi,

Script is passing with below changes and git pull request:
1. Added speed in testbed file 
duts {
  id: "dut"
  vendor: JUNIPER
  ports {
    id: "port1"
    speed: S_400GB
  }
  ports {
    id: "port2"
  }
}

2. Created pull request for code changes : https://github.com/openconfig/featureprofiles/pull/941
Closing this issue .

Thanks,
Avaneesh
