### ISSUE TITLE
qos_output_queue_counters_test.go script missing to configure inet classifiers configs on dut

### ISSUE THREAD

**Issue by stthummuri** [openconfig/featureprofiles#918]
dp-1.4_QoS_Interface_Output_Queue_Counters script qos_output_queue_counters_test.go is missing to configure inet classifiers on the ingress interface depending on the packet code points to map the traffic to respective queues.

Currently with the script packets are not counted against queue 1, 2 ,5 6, because, custom classifiers are not configured on the ingress interface to map the traffic to these queues.Default classifiers on the ingress interface always maps traffic to only queue 0 and queue 3 and so the traffic is seen only in queue 0 and queue 3.

When below configs are applied traffic is spread across different queues. This needs to be taken care of in the script.

set class-of-service classifiers inet-precedence 8q-inet forwarding-class af1 loss-priority low code-points 001
set class-of-service classifiers inet-precedence 8q-inet forwarding-class af2 loss-priority low code-points 010
set class-of-service classifiers inet-precedence 8q-inet forwarding-class af3 loss-priority low code-points 011
set class-of-service classifiers inet-precedence 8q-inet forwarding-class af4 loss-priority low code-points 100
set class-of-service classifiers inet-precedence 8q-inet forwarding-class be1 loss-priority low code-points 000
set class-of-service classifiers inet-precedence 8q-inet forwarding-class nc1 loss-priority low code-points 111
set class-of-service forwarding-classes class af1 queue-num 4
set class-of-service forwarding-classes class af2 queue-num 1
set class-of-service forwarding-classes class af3 queue-num 5
set class-of-service forwarding-classes class af4 queue-num 2
set class-of-service forwarding-classes class be1 queue-num 0
set class-of-service forwarding-classes class nc1 queue-num 3
set class-of-service interfaces et-0/0/5 unit 0 classifiers inet-precedence 8q-inet

**Comment by aredmon8551** [comment]
The issue here is that model uses a string for queue name rather than an int.  Pull request incoming to suggest a change to the model.

`
/openconfig-qos:qos/queues/queue,nil
/openconfig-qos:qos/queues/queue/config,nil
/openconfig-qos:qos/queues/queue/config/name,string
/openconfig-qos:qos/queues/queue/name,leafref

/openconfig-qos:qos/forwarding-groups/forwarding-group/config/output-queue,leafref
/openconfig-qos:qos/forwarding-groups/forwarding-group/config/unicast-output-queue,leafref
`

**Comment by sezhang2** [comment]
@aredmon8551 

Here is the change I am going to apply to the device per discussion. 

sezhang@xx22.den85-re0# show | compare 
[edit class-of-service classifiers]
     inet-precedence external-classifier { ... }
+    inet-precedence 8q-inet {
+        forwarding-class af1 {
+            loss-priority low code-points 001;
+        }
+        forwarding-class af2 {
+            loss-priority low code-points 010;
+        }
+        forwarding-class af3 {
+            loss-priority low code-points 011;
+        }
+        forwarding-class af4 {
+            loss-priority low code-points 100;
+        }
+        forwarding-class be1 {
+            loss-priority low code-points 000;
+        }
+        forwarding-class nc1 {
+            loss-priority low code-points 111;
+        }
+    }
[edit class-of-service interfaces et-*/*/* unit * classifiers]
-       inet-precedence inet-classifier;
+       inet-precedence 8q-inet;
[edit class-of-service interfaces]
+    ge-*/*/* {
+        unit * {
+            classifiers {
+                inet-precedence 8q-inet;
+            }
+        }                              
+    }
+    gr-*/*/* {
+        unit * {
+            classifiers {
+                inet-precedence 8q-inet;
+            }
+        }
+    }
+    xe-*/*/* {
+        unit * {
+            classifiers {
+                inet-precedence 8q-inet;
+            }
+        }
+    }
[edit class-of-service interfaces ae* unit * classifiers]
-       inet-precedence inet-classifier;
+       inet-precedence 8q-inet;
 
{master}[edit]
sezhang@xx22.den85-re0# commit check 
re0: 
configuration check succeeds
re1: 
configuration check succeeds
 
{master}[edit]
sezhang@xx22.den85-re0# 
 
{master}[edit]
sezhang@xx22.den85-re0# run show version 
Hostname: xx22.den85-re0
Model: ptx10008
Junos: 22.3X80-D30.10-EVO
Yocto: 3.0.2
Linux Kernel: 5.2.60-yocto-standard-g7ea8cf7
JUNOS-EVO OS 64-bit [junos-evo-install-ptx-x86-64-22.3X80-D30.10-EVO]
 
{master}[edit]
sezhang@xx22.den85-re0#
