### ISSUE TITLE
interface-ref clafirication while attaching classifer to interface

### ISSUE THREAD

**Issue by azubaidhar** [openconfig/featureprofiles#947]
Hi [sezhang2](https://github.com/openconfig/featureprofiles/commits?author=sezhang2)

https://github.com/openconfig/featureprofiles/blob/main/feature/experimental/qos/ate_tests/qos_policy_config_test/qos_policy_config_test.go

 I see a config problem while attaching classifier to an interface.   TestQoSInputIntfClassifierConfig uses interfaceId to bind classifier,. I think , interface-ref is also needed like sample below.

set openconfig-qos:qos interfaces interface et-0/0/0 interface-ref config interface et-0/0/0
set openconfig-qos:qos interfaces interface et-0/0/0 interface-ref config subinterface 0

Can you please clarify or fix the script.

Thanks
Abdul Zubaidhar .A

**Comment by sezhang2** [comment]
@azubaidhar Can you ping sezhang@google.com via google chat to have a discussion?

**Comment by azubaidhar** [comment]
Able to change script with interface-ref, sample added in https://github.com/openconfig/featureprofiles/pull/969

**Comment by azubaidhar** [comment]
Able to change script with interface-ref, sample added in https://github.com/openconfig/featureprofiles/pull/969
