### ISSUE TITLE
TE-3.1 : base_hierarchical_route_installation_test checking interface-ref for IP next-hop

### ISSUE THREAD

**Issue by trathod1** [openconfig/featureprofiles#964]
In the script base_hierarchical_route_installation_test, interface-ref is checked for IP next-hop (indirect-nexthops) at - 

https://github.com/openconfig/featureprofiles/blob/main/feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go#L322-L324

https://github.com/openconfig/featureprofiles/blob/main/feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go#L355-L357

> 		if nh.GetInterfaceRef().GetInterface() == "" {
> 			t.Errorf("next-hop interface-ref/interface not found")
> 		}

Should this check be removed from here as indirect next-hop can be resolved from multiple interfaces ? Here in this script case, this prefix  `198.51.100.0/24` has next-hop `203.0.113.1/32` which can be resolved by multiple interfaces. Verifying interface-ref for indirect next-hops may not be valid.

I understand, interface-ref check should be applicable only for direct next-hops (interface+MAC) for gRIBI.

**Comment by xw-g** [comment]
As the comment in the code mentioned, some vendor OS might flatten the resolution. So, instead of just removing the interface check, maybe we should put it under the condition of say `if got := nh.GetIpAddress(); got != atePort2.IPv4 `?

**Comment by trathod1** [comment]
We can move it under the `if` condition, where `if got != ateIndirectNH`, then interface-ref will be checked -

```Go
  315         if got := nh.GetIpAddress(); got != atePort2.IPv4 {
  316             // for devices that return the nexthop without resolving it recursively. For a->b->c the device returns b
  317             // note that b->c is validated in the next code block
  318             if got != ateIndirectNH {
+ 319                 if nh.GetInterfaceRef().GetInterface() == "" {
+ 320                     t.Errorf("next-hop interface-ref/interface not found")
+ 321                 }   
  322                 t.Errorf("next-hop is incorrect: got %v, want %v or %v ", got, ateIndirectNH, atePort2.IPv4)
  323             }                                                                                                                                    
_ 324         } 
```

Similarly at Line-355 check - 

```Go
  352         if got, want := nh.GetIpAddress(), atePort2.IPv4; got != want {
+ 353             if nh.GetInterfaceRef().GetInterface() == "" {
+ 354                 t.Errorf("next-hop interface-ref/interface not found")
+ 355             }
  356             t.Errorf("next-hop is incorrect: got %v, want %v", got, want)
_ 357         }
```

**Comment by xw-g** [comment]
Can you help file a PR and let's review it further there? Thanks.

**Comment by trathod1** [comment]
Raised https://github.com/openconfig/featureprofiles/pull/1168 for this.

**Comment by xw-g** [comment]
https://github.com/openconfig/featureprofiles/pull/1168 merged
